version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: nexcrm_postgres
    environment:
      POSTGRES_USER: nexcrm
      POSTGRES_PASSWORD: nexcrm_secret
      POSTGRES_DB: nexcrm
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexcrm"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nexcrm_redis
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
